// ---------------------------------------------------------------------------
// CurbOps — /api/analytics
// Serves the pre-computed daily parking-impact trends generated by
// CurbOps_Pipeline/generate_analytics.py (data/analytics.json).
// If the file is absent we return { daily: [] } so the City Trends panel can
// render an honest empty-state instead of erroring — never fake data.
// ---------------------------------------------------------------------------

import { NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';
import type { AnalyticsPayload } from '@/lib/dashboard/types';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET() {
  const file = path.join(process.cwd(), 'data', 'analytics.json');
  try {
    const raw = await fs.readFile(file, 'utf-8');
    const data = JSON.parse(raw) as AnalyticsPayload;
    return NextResponse.json(data, {
      headers: { 'Cache-Control': 'no-store, max-age=0' },
    });
  } catch {
    // File doesn't exist (or unreadable) → empty payload, UI shows empty-state.
    return NextResponse.json({ daily: [] } satisfies AnalyticsPayload, {
      headers: { 'Cache-Control': 'no-store, max-age=0' },
    });
  }
}
